=== AswathKumar123/playwright-Automation/response-schemas/goals/GET_goals_schemas.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "category": {
        "type": "string"
      },
      "current": {
        "type": "number"
      },
      "target": {
        "type": "number"
      },
      "monthlyContribution": {
        "type": "number"
      },
      "targetDate": {
        "type": "string",
        "format": "date"
      },
      "icon": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "title",
      "category",
      "current",
      "target",
      "monthlyContribution",
      "targetDate",
      "icon"
    ]
  }
}

=== AswathKumar123/playwright-Automation/mocks/goalsMock.json
[
    {
        "id": "retirement",
        "title": "Aswath_Retirement",
        "category": "retirement",
        "current": 182500,
        "target": 5200000,
        "monthlyContribution": 500,
        "targetDate": "2027-10-01",
        "icon": "sun"
    },
    {
        "id": "emergency",
        "title": "Aswath_Emergency fund",
        "category": "savings",
        "current": 14900,
        "target": 202000,
        "monthlyContribution": 451,
        "targetDate": "2027-09-01",
        "icon": "shield"
    },
    {
        "id": "college",
        "title": "Aswath_College savings",
        "category": "education",
        "current": 7220,
        "target": 600600,
        "monthlyContribution": 301,
        "targetDate": "2042-08-01",
        "icon": "book"
    }
]
